name: pkgcheck

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Run pkgcheck
        uses: pkgcore/pkgcheck-action@v1
        with:
          args: --keywords=-RedundantVersion,-NonsolvableDepsInDev
