name: pkgcheck

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run pkgcheck
        uses: pkgcore/pkgcheck-action@v1
        with:
          args: --keywords=-RedundantVersion,-NonsolvableDepsInDev
